-- Seed Data: Sample listings
-- Description: Test property listings for development
-- Created: 2026-02-04

INSERT INTO listings (
  id,
  host_id,
  title,
  description,
  property_type,
  room_type,
  address_line1,
  city,
  state_province,
  country,
  postal_code,
  latitude,
  longitude,
  max_guests,
  num_bedrooms,
  num_beds,
  num_bathrooms,
  price_per_night,
  cleaning_fee,
  minimum_nights,
  maximum_nights,
  instant_booking,
  cancellation_policy,
  is_published,
  is_available,
  amenities,
  check_in_time,
  check_out_time,
  has_smoke_alarm,
  has_carbon_monoxide_alarm,
  has_fire_extinguisher,
  has_first_aid_kit,
  average_rating,
  total_reviews
) VALUES
  -- Listing 1: Beach House by Emily (Superhost)
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    '33333333-3333-3333-3333-333333333333',
    'Stunning Beachfront Villa with Ocean Views',
    'Wake up to the sound of waves in this luxurious 3-bedroom beachfront villa. Features include a private pool, outdoor dining area, and direct beach access. Perfect for families or groups looking for a memorable coastal getaway. The spacious living area opens to a panoramic ocean view terrace.',
    'villa',
    'entire_place',
    '123 Coastal Drive',
    'Malibu',
    'California',
    'United States',
    '90265',
    34.0259,
    -118.7798,
    8,
    3,
    4,
    2.5,
    450.00,
    75.00,
    2,
    14,
    false,
    'moderate',
    true,
    true,
    '["WiFi", "Pool", "Beach Access", "Kitchen", "Parking", "Air Conditioning", "Washer", "Dryer", "Ocean View", "BBQ Grill", "Outdoor Dining"]'::jsonb,
    '16:00:00',
    '11:00:00',
    true,
    true,
    true,
    true,
    4.9,
    47
  ),
  
  -- Listing 2: City Apartment by Emily
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    '33333333-3333-3333-3333-333333333333',
    'Modern Downtown Loft in Arts District',
    'Stylish industrial loft in the heart of the arts district. High ceilings, exposed brick, and floor-to-ceiling windows. Walking distance to galleries, restaurants, and nightlife. Perfect for creative professionals or couples.',
    'loft',
    'entire_place',
    '456 Arts Boulevard',
    'Los Angeles',
    'California',
    'United States',
    '90012',
    34.0522,
    -118.2437,
    4,
    2,
    2,
    1.0,
    185.00,
    40.00,
    1,
    30,
    true,
    'flexible',
    true,
    true,
    '["WiFi", "Kitchen", "Parking", "Air Conditioning", "Workspace", "Smart TV", "Coffee Maker", "City View"]'::jsonb,
    '15:00:00',
    '11:00:00',
    true,
    true,
    true,
    true,
    4.8,
    32
  ),
  
  -- Listing 3: Mountain Cabin by James
  (
    'cccccccc-cccc-cccc-cccc-cccccccccccc',
    '44444444-4444-4444-4444-444444444444',
    'Cozy Mountain Cabin with Fireplace',
    'Escape to the mountains in this charming wooden cabin. Features a stone fireplace, rustic decor, and a large deck with mountain views. Ideal for hikers and nature lovers. Close to ski resorts in winter.',
    'cabin',
    'entire_place',
    '789 Pine Ridge Road',
    'Big Bear',
    'California',
    'United States',
    '92315',
    34.2439,
    -116.9114,
    6,
    2,
    3,
    1.5,
    220.00,
    50.00,
    2,
    7,
    false,
    'strict',
    true,
    true,
    '["WiFi", "Fireplace", "Kitchen", "Parking", "Heating", "Mountain View", "BBQ Grill", "Deck", "Hiking Trails"]'::jsonb,
    '16:00:00',
    '10:00:00',
    true,
    true,
    true,
    true,
    4.7,
    28
  ),
  
  -- Listing 4: Private Room by Alex
  (
    'dddddddd-dddd-dddd-dddd-dddddddddddd',
    '55555555-5555-5555-5555-555555555555',
    'Private Room in Friendly Home',
    'Comfortable private bedroom in a shared house with friendly hosts. Shared kitchen and living room access. Great for solo travelers on a budget who want to experience local living. Your hosts can provide insider tips!',
    'house',
    'private_room',
    '321 Maple Street',
    'San Diego',
    'California',
    'United States',
    '92101',
    32.7157,
    -117.1611,
    2,
    1,
    1,
    1.0,
    65.00,
    15.00,
    1,
    30,
    true,
    'flexible',
    true,
    true,
    '["WiFi", "Kitchen", "Parking", "Air Conditioning", "Workspace", "Shared Living Room"]'::jsonb,
    '14:00:00',
    '11:00:00',
    true,
    true,
    true,
    true,
    4.6,
    15
  ),
  
  -- Listing 5: Luxury Condo by James
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
    '44444444-4444-4444-4444-444444444444',
    'Luxury Penthouse with Rooftop Pool',
    'Ultra-modern penthouse with breathtaking city skyline views. Features include a private rooftop pool, gourmet kitchen, smart home technology, and premium furnishings. Perfect for special occasions or business executives.',
    'condo',
    'entire_place',
    '999 Skyline Tower',
    'San Francisco',
    'California',
    'United States',
    '94102',
    37.7749,
    -122.4194,
    4,
    2,
    2,
    2.0,
    550.00,
    100.00,
    3,
    10,
    false,
    'super_strict',
    true,
    true,
    '["WiFi", "Pool", "Kitchen", "Parking", "Air Conditioning", "Gym", "Elevator", "Smart Home", "Rooftop Access", "City View", "Concierge"]'::jsonb,
    '17:00:00',
    '11:00:00',
    true,
    true,
    true,
    true,
    4.95,
    22
  );

-- Update listing statistics
UPDATE listings SET total_views = 342 WHERE id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
UPDATE listings SET total_views = 289 WHERE id = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
UPDATE listings SET total_views = 156 WHERE id = 'cccccccc-cccc-cccc-cccc-cccccccccccc';
UPDATE listings SET total_views = 98 WHERE id = 'dddddddd-dddd-dddd-dddd-dddddddddddd';
UPDATE listings SET total_views = 267 WHERE id = 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee';

UPDATE listings SET total_bookings = 47 WHERE id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
UPDATE listings SET total_bookings = 32 WHERE id = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
UPDATE listings SET total_bookings = 28 WHERE id = 'cccccccc-cccc-cccc-cccc-cccccccccccc';
UPDATE listings SET total_bookings = 15 WHERE id = 'dddddddd-dddd-dddd-dddd-dddddddddddd';
UPDATE listings SET total_bookings = 22 WHERE id = 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee';

COMMENT ON TABLE listings IS 'Sample listings loaded: 5 properties across different types and price ranges';
